# This file was created automatically with `myst init --gh-pages` 🪄 💚
# Ensure your GitHub Pages settings for this repository are set to deploy with **GitHub Actions**.

name: MyST GitHub Pages Deploy
on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  BASE_URL: /${{ github.event.repository.name }}


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MyST
        run: python3 -m pip install mystmd

      - name: Build HTML Assets
        run: myst build --strict --ci --html

      - name: Install jupyterlite dependencies
        run: python3 -m pip install -r requirements-lite.txt

      - name: Build site for jupyterlite
        run: |
          jupyter lite build --contents notebooks --output-dir ./_build/html/lite

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
